/**
 * English (US) label dictionary for localization keys.
 * @format
 */

/**
 * @type {Record<string, string>}
 */
const labels = {
	"profile.uuid": "UUID",
	"profile.image": "Photo",
	"profile.active": "Status",
	"profile.created_at": "Created Date",
	"profile.updated_at": "Last Update Date",
	"profile.created_by": "Created By",
	"profile.updated_by": "Last Updated By",
	"profile.responsible_staff": "Responsible Staff",
	"profile.first_name": "First Name",
	"profile.last_name": "Last Name",
	"profile.gender": "Gender",
	"profile.room": "Room",
	"profile.location": "Location",
	"profile.date_of_birth": "Date of Birth",
	"profile.birthplace": "Birthplace",
	"profile.nationality": "Nationality",
	"profile.identification_number": "Identification Number",
	"profile.address": "Address",
	"profile.blood_type": "Blood Type",
	"profile.home_phone": "Phone - Home",
	"profile.mobile_phone": "Phone - Mobile",
	"profile.relatives": "Relatives",
	"update_log": "Update Log",
	"update_log.date": "Date",
	"update_log.user_id": "User ID",
	"update_log.fields": "Fields",
	"health.category.independence": "Independence",
	"health.category.mobility": "Mobility",
	"health.category.motor-function": "Motor Function",
	"health.category.vision": "Vision",
	"health.category.hearing": "Hearing",
	"health.category.cognitive-status": "Cognitive Status",
	"health.independence.independent": "Independent in daily activities",
	"health.independence.partial-assistance": "Needs partial assistance",
	"health.independence.full-care": "Requires full assistance",
	"health.mobility.normal": "Normal",
	"health.mobility.bedridden": "Bedridden",
	"health.mobility.wheelchair-dependent": "Wheelchair-dependent",
	"health.mobility.crutches-or-cane": "Uses crutches or cane",
	"health.mobility.slow-or-unstable-walking": "Slow or unstable walking",
	"health.motor-function.normal-hand-function": "Normal hand function",
	"health.motor-function.limited-hand-function": "Limited or no hand function",
	"health.motor-function.fine-motor-difficulty": "Difficulty with fine motor skills (e.g., buttoning clothes)",
	"health.vision.normal": "Normal",
	"health.vision.impaired": "Impaired",
	"health.vision.blind": "Blind",
	"health.hearing.normal": "Normal",
	"health.hearing.impaired": "Impaired",
	"health.hearing.deaf": "Deaf",
	"health.cognitive-status.normal-cognition": "Normal cognition",
	"health.cognitive-status.mild-cognitive-impairment": "Mild cognitive impairment",
	"health.cognitive-status.dementia-alzheimers-symptoms": "Dementia or Alzheimer's symptoms",
	"health.free-text.chronic-illness": "Chronic conditions",
	"health.free-text.chronic-illness.notes": "Chronic conditions description",
	"health.free-text.medications": "Medications",
	"health.free-text.medications.notes": "Medications in use",
	"health.free-text.allergies": "Allergies",
	"health.free-text.allergies.notes": "Allergy details",
	"health.free-text.medical-history": "Medical history",
	"health.free-text.medical-history.notes": "Surgeries, injuries, and related history",
	"health.equipment.artificial-pacemaker": "Artificial Pacemaker",
	"health.equipment.catheter": "Catheter",
	"health.equipment.chemotherapy-port": "Chemotherapy Port",
	"health.equipment.cochlear-implant": "Cochlear Implant",
	"health.equipment.contact-lens": "Contact Lens",
	"health.equipment.cpap": "CPAP",
	"health.equipment.eyeglasses": "Eyeglasses",
	"health.equipment.hearing-aid": "Hearing Aid",
	"health.equipment.cardio-defibrillator-iacd": "CardioDefibrillator (IACD)",
	"health.equipment.insulin-pump": "Insulin Pump",
	"health.equipment.oxygen": "Oxygen",
	"health.equipment.prosthetic-heart-valves": "Prosthetic Heart Valves",
	"health.equipment.bioprosthetic": "Bioprosthetic",
	"gender.short.male": "M",
	"gender.short.female": "F",
	"gender.long.male": "Male",
	"gender.long.female": "Female",
	"residents.column.name": "Name",
	"residents.column.responsible_staff": "Responsible Staff",
	"residents.column.birth_date": "Birth Date",
	"residents.column.gender": "Gender",
	"residents.column.room": "Room",
	"residents.column.last_visit": "Last Visit",
	"residents.search.name": "Search by name",
	"visits": "Visits",
	"visits.date": "Date",
	"visits.caretaker": "Caretaker",
	"visits.actions": "Actions",
	"visits.last_visit": "Last Visit",
	"visits.relative": "Relative",
	"visits.add.title": "Add Visit",
	"visits.add.subtitle": "Select the care actions performed during this visit",
	"visits.add.submit": "Save Visit",
	"visits.add.cancel": "Cancel",
	"visits.action.checked": "Checked",
	"visits.category.medical-care": "Medical Care",
	"visits.category.personal-care": "Personal Care",
	"visits.category.housekeeping": "Housekeeping",
	"visits.category.supportive-services": "Supportive Services",
	"visits.group.vital-measurements": "Vital measurements",
	"visits.group.personal-hygiene": "Personal hygiene",
	"visits.group.mobility-support": "Mobility support",
	"visits.group.environmental-hygiene": "Environmental hygiene",
	"visits.group.meal-service-dietary-monitoring": "Meal service & dietary monitoring",
	"visits.group.activity-support": "Activity support",
	"visits.action.medication-administration": "Medication administration",
	"visits.action.blood-pressure": "Blood pressure",
	"visits.action.pulse": "Pulse",
	"visits.action.temperature": "Temperature",
	"visits.action.oxygen-saturation": "Oxygen saturation",
	"visits.action.wound-care-dressing": "Wound care & dressing",
	"visits.action.injections-iv-therapy": "Injections / IV therapy",
	"visits.action.medical-reporting-referrals": "Medical reporting & referrals",
	"visits.action.in-bed-body-cleaning": "In-bed body cleaning",
	"visits.action.bathing-shower-assistance": "Bathing / shower assistance",
	"visits.action.hair-cutting-care": "Hair cutting & care",
	"visits.action.nail-care": "Nail care",
	"visits.action.toileting-incontinence-care": "Toileting & incontinence care",
	"visits.action.dressing-undressing-assistance": "Dressing & undressing assistance",
	"visits.action.feeding-assistance": "Feeding assistance",
	"visits.action.assisted-walking": "Assisted walking",
	"visits.action.transfers-bed-to-chair": "Transfers (bed to chair)",
	"visits.action.wheelchair-use": "Wheelchair use",
	"visits.action.companionship-emotional-support": "Companionship & emotional support",
	"visits.action.room-cleaning-tidying": "Room cleaning & tidying",
	"visits.action.laundry-clothing-care": "Laundry & clothing care",
	"visits.action.bed-linen-changes": "Bed linen changes",
	"visits.action.disinfection": "Disinfection",
	"visits.action.odor-control": "Odor control",
	"visits.action.shared-space-maintenance": "Shared space maintenance",
	"visits.action.regular-meals": "Regular meals",
	"visits.action.tube-feeding": "Tube feeding",
	"visits.action.iv-nutrition": "IV nutrition",
	"visits.action.other-nutrition-methods": "Other nutrition methods",
	"visits.action.meal-refused": "Meal refused / not eaten",
	"visits.action.rehabilitation-exercises": "Rehabilitation exercises",
	"visits.action.group-activities": "Group activities",
};

export default labels;
